// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Palfinger.ProductManual.Infrastructure.Data;

namespace Palfinger.ProductManual.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ProductManualDbContext))]
    [Migration("20210817201654_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Manual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manual");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.MtoM.ProductConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ConfigurationId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManualId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("ManualId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductConfiguration");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Configuration", b =>
                {
                    b.HasOne("Palfinger.ProductManual.Domain.Product", null)
                        .WithMany("Configurations")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.MtoM.ProductConfiguration", b =>
                {
                    b.HasOne("Palfinger.ProductManual.Domain.Configuration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId");

                    b.HasOne("Palfinger.ProductManual.Domain.Manual", null)
                        .WithMany("ProductConfigurations")
                        .HasForeignKey("ManualId");

                    b.HasOne("Palfinger.ProductManual.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Configuration");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Manual", b =>
                {
                    b.Navigation("ProductConfigurations");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Product", b =>
                {
                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
