// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Palfinger.ProductManual.Infrastructure.Data;

namespace Palfinger.ProductManual.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ProductManualDbContext))]
    [Migration("20210816204334_addManualWithManyProducts")]
    partial class addManualWithManyProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2");

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Manual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manual");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ManualId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManualId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Product", b =>
                {
                    b.HasOne("Palfinger.ProductManual.Domain.Manual", null)
                        .WithMany("Products")
                        .HasForeignKey("ManualId");
                });

            modelBuilder.Entity("Palfinger.ProductManual.Domain.Manual", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
